<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />
<script src="<?php echo base_url(); ?>resources/js/ajaxfileupload.js" type="text/javascript"></script>
<script src="<?php echo base_url(); ?>resources/js/jquery.datepick-es.js" type="text/javascript"></script> 

<style>
    #usuario-lightbox-ya-hise{
        padding: 15px;	
        border-radius: 5px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        border: 1px solid #ccc;
        color: #404040;
        font:12px open_sansregular;
        position: relative;
        background-color: #f5f5f5;
        width: 350px;
    }

    #usuario-lightbox-ya-hise label{
        color: #404040;
        font-size:14px;
        display: block;
    }

    #usuario-lightbox-ya-hise input[type=text]{
        background-color: #f9f9f9;
        border: 2px solid #b5b5b5;
        moz-border-radius: 5px;
        webkit-border-radius: 5px; 
        border-radius: 5px;
        outline:none;
        color: black;
        padding: 10px 10px;
        font-family:open_sansregular; 
    }

    #usuario-lightbox-ya-hise input[type=text]:focus
    { outline:none;
      border: 2px solid #c60200;
      background-color: #fbfbfb;
      -webkit-box-shadow: 0px 0px 5px #c60200;
      -moz-box-shadow:    0px 0px 5px #c60200;
      box-shadow:         0px 0px 5px #c60200;
    }

    #usuario-lightbox-ya-hise-t1, #usuario-lightbox-ya-hise-t2{
        font:18px univers_condensedbold;
        text-transform: uppercase;
    }

    #usuario-lightbox-ya-hise-t2{
        color: #c60200; 
    }

    #usuario-lightbox-ya-hise-content{
        margin-top: 15px;	
        position: relative;	
    }

    #fromCalendar{
        margin-top:5px; 
    }

    #usuario-lightbox-ya-hise-kilometraje{
        margin-top: 10px;
    }

    #usuario-lightbox-ya-hise-adjunto{
        margin-top: 10px;
        float: left;
    }

    #usuario-lightbox-ya-hise-submit{
        float:right;
        margin-top: 10px;
        position: relative;
        margin-right: 10px;
    }

    #usuario-lightbox-ya-hise input[type=submit], #usuario-lightbox-ya-hise input[type=button] {
        float:right;
        cursor: pointer;
        background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ebe8eb), color-stop(1, #a8a5a8) );
        background:-moz-linear-gradient( center top, #ebe8eb 5%, #a8a5a8 100% );
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ebe8eb', endColorstr='#a8a5a8');
        background-color:#ebe8eb;
        -moz-border-radius:5px;
        -webkit-border-radius:5px;
        border-radius:5px;
        border:1px solid #8f8f8f;
        display:inline-block;
        color:#4a4a4a;
        font-family:arial;
        font-size:15px;
        font-weight:bold;
        padding:6px 24px;
        text-decoration:none;
        text-shadow:1px 1px 0px #c7c7c7;
    }
    #usuario-lightbox-ya-hise input[type=submit]:hover, #usuario-lightbox-ya-hise input[type=button]:hover {
        background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #a8a5a8), color-stop(1, #ebe8eb) );
        background:-moz-linear-gradient( center top, #a8a5a8 5%, #ebe8eb 100% );
        filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#a8a5a8', endColorstr='#ebe8eb');
        background-color:#a8a5a8;
    }
    #usuario-lightbox-ya-hise input[type=submit]:active, #usuario-lightbox-ya-hise input[type=button]:active {
        position:relative;
        top:1px;
    }
    /* This imageless css button was generated by CSSButtonGenerator.com */

    div.ui-widget{
        font-size: 14px;
    }

    .ajax_img_loader{
        position: absolute;
        bottom: 10px;
        right: -20px;
        display: none;
    }

    #tarea-realizada label.form-invalid, #tarea-realizada label.form-valid{
        margin-top: 0px;
        font-size: 11px;
    }  
</style>
<script>
    $(document).ready(function(){

        var currentDate = new Date();
        var day = currentDate.getDate();
        var month = currentDate.getMonth() + 1;
        var year = currentDate.getFullYear();
        var fecha = year+"-"+month+"-"+day;
        $('#tarea-realizada-fecha').val( fecha );
	
        $("#tarea-realizada-fecha").datepicker({ appendText: "(aaaa-mm-dd)", altField: "#tarea-realizada-fecha", altFormat: 'yy-mm-dd', rangeSelect: false, maxDate: "+0D" });
    
        $('#tarea-realizada-fecha').change(function(){
            var fecha = $(this).val();
            var arrayFecha = fecha.split('-');
            var formatFecha = new Date(arrayFecha[0], arrayFecha[1]-1, arrayFecha[2]);
            var fechaActual = new Date();
            var diff = Math.abs(formatFecha.getTime() - fechaActual.getTime());
            var diffDias  = Math.ceil( diff/(60*60*24*1000)) -1; 		
            $('#tarea-realizada-kilometraje').val( <?php echo $vehiculo->kilometraje; ?> - (diffDias * 34) ); //kilometraje actual - diff * kilometraje diario ponderado de la ciudad
        });
        
    });
    
    
    //valida el formulario de la tarea que se va a realizar
    $(function() {
        $("#tarea-realizada").validate({
            rules: {
                tarea_realizada_kilometraje:{
                    required: true,
                    number: true
                },
                tarea_realizada_fecha: {
                    required: true
                }
            },
            messages: {
                tarea_realizada_kilometraje:{
                    required: "*debes escribir el kilometraje en que realizaste el mantenimiento",
                    number: "*el kilometraje debe ser un número"
                },
                tarea_realizada_fecha: {
                    required: "*debes escribir la fecha en que realizaste el mantenimiento"
                }
            },
            invalidHandler: function (form, validator) {
                var errors = validator.numberOfInvalids();
                if (errors) {
                    var message = errors == 1 ? 'Se encontró el siguiente error:\n' : 'Se encontraron los siguientes ' + errors + ' errores:\n';
                    var errors = "";
                    if (validator.errorList.length > 0) {
                        for (x = 0; x < validator.errorList.length; x++) {
                            errors += "\n\u25CF " + validator.errorList[x].message
                        }
                    }
                    alert(message + errors)
                }
                validator.focusInvalid()
            },
            errorClass: "form-invalid",
            validClass: "form-valid",
            submitHandler: function (form) {
                $(form).bind('click');
                $('.ajax_img_loader', form).show();
                var padre = $('.smv_tarea_realizar.tarea_realizar_selected');
                var id_tarea = $('#tarea-realizada-id-tarea', form).val();
                var id_usuario_vehiculo = $('#tarea-realizada-id-usuario_vehiculo', form).val();
                var kilometraje = $('#tarea-realizada-kilometraje', form).val();
                var fecha = $('#tarea-realizada-fecha', form).val();
                $.ajaxFileUpload({
                    url: "/usuario/tarea_realizada_ajax",
                    secureuri      :false,
                    fileElementId  :'tarea_realizada_adjunto',
                    dataType    : 'json',
                    data: {
                        'id_tarea': id_tarea,
                        'id_usuario': id_usuario_vehiculo,
                        'kilometraje': kilometraje,
                        'fecha': fecha
                    },
                    success: function (data, status){
                        //sube el adjunto
                        if(data.status==true){
                            padre.hide('slow', function(){ padre.remove(); });
                            var temp = (data.msg).split("|");
                            var divHecho = $('ul','.usuario-div-smv-hecho-tareas');
                            var spanIdTarea = $("<span>").text(temp[1]).addClass('usuario-div-smv-hecho-tareas-id-tarea');
                            var spanRealizado = $("<span>").text('Deshacer').addClass('usuario-span-tareas-deshacer');
                            var tareaRealizada =$("<li>").text(temp[2]+'........').addClass('usario-li-tarea-realizada');
                            tareaRealizada.append(spanIdTarea);
                            var spanFecha = $("<span>").text(temp[0]+' |');
                            spanFecha.append(spanRealizado);
                            if(temp[3]){ 
                                var AAdjunto = $("<a>").text('Adjunto').attr('href',temp[3]).attr('target', '_blank');
                                var spanAdjunto = $("<span>").text(' | ').addClass('usuario-span-tareas-adjunto');
                                spanAdjunto.append(AAdjunto); 
                                spanFecha.append(spanAdjunto);}
                            tareaRealizada.append(spanFecha); 
                            divHecho.prepend(tareaRealizada);
                            divHecho.show('slow', function(){ divHecho.add(); }); 
                        }else{
                            alert(data.msg);
                        }
                    }
                });
                $('.ajax_img_loader', form).hide();
                $(form).unbind('click');
                $('.tarea_realizada_cancelar').trigger('click');
            }
        });
    });
    

</script>
<div id="usuario-lightbox-ya-hise">
    <div id="usuario-lightbox-ya-hise-t1">Cuándo fue la última vez que realizaste</div>
    <div id="usuario-lightbox-ya-hise-t2"><?php echo $tarea->nombre; ?></div>
    <form id="tarea-realizada" method="post" action="">
        <input type="hidden" value="<?php echo $tarea->id_servicio; ?>" name="tarea_realizada_id_tarea" id="tarea-realizada-id-tarea" />
        <input type="hidden" value="<?php echo $vehiculo->id_usuario_vehiculo; ?>" name="tarea_realizada_id_usuario_vehiculo" id="tarea-realizada-id-usuario_vehiculo" />
        <div id="usuario-lightbox-ya-hise-content">
            <div id="usuario-lightbox-ya-hise-fecha">
                <label>Cuándo realizaste el mantenimiento?</label>
                <input name="tarea_realizada_fecha" id="tarea-realizada-fecha" type="text" value=""/>
            </div> 

            <div id="usuario-lightbox-ya-hise-kilometraje">
                <label>Kilometraje:</label>
                <input name="tarea_realizada_kilometraje" id="tarea-realizada-kilometraje" type="text" value="<?php echo $vehiculo->kilometraje; ?>"/>
            </div>


        </div>

        <div id="usuario-lightbox-ya-hise-adjunto">
            <label>Adjunta el recibo o comprobante: (*opcional)</label>
            <input name="tarea_realizada_adjunto" id="tarea_realizada_adjunto" type="file" />
        </div>

        <div  id="usuario-lightbox-ya-hise-submit">
            <input type="submit" value="Enviar" id="tarea_realizada_submit"  class="tarea_realizada_submit"/>
            <input type="button" value="Cancelar" id="tarea_realizada_cancelar" class="tarea_realizada_cancelar"/>
            <img src="<?php echo base_url(); ?>resources/images/login/ajax-loader.gif" class="ajax_img_loader" />
        </div>   
        <div class="clear"></div>
    </form>   
</div>